name: protein_fitness_prediction
channels:
  - pytorch
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - biopython=1.78
  - cudatoolkit
  - filelock=3.0.12
  - matplotlib-base=3.3.*
  - networkx=2.4
  - numpy=1.18.5
  - pandas=1.1.*
  - pathlib2=2.3.*
  - pip=20.2.3
  - python=3.7.6
  - pytorch=1.4.0
  - scikit-learn=0.23.1
  - scikit-optimize=0.8.1
  - seaborn=0.10.*
  - tqdm=4.50.*
  - pip:
    - fair-esm==0.3.*
    - evcouplings==0.1.*
    - numba==0.51.*
    - scipy==1.4.*
    - tensorboard==2.2.*
    - tensorboard-plugin-wit==1.7.*
    - tensorflow==2.2.0
    - tensorflow-addons==0.10.*
    - tensorflow-estimator==2.2.*
    - tensorflow-probability==0.10.*
